name: Deploy to S3  # Name of the workflow

on:
  push:
    branches:
      - main  # This workflow runs when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # The job will run on an Ubuntu-based GitHub Actions runner

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Pulls the latest code from the repo

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}  # Access key stored in GitHub Secrets
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}  # Secret key stored in GitHub Secrets
          aws-region: ${{ secrets.AWS_REGION }}  # AWS region where the S3 bucket is located

      - name: Upload Files to S3
        run: |
          aws s3 sync . s3://${{ secrets.S3_BUCKET_NAME }}    # Syncs local files to S3, deleting extra files in S3
